### ISSUE TITLE
LookupError: unknown encoding: cp65001

### ISSUE THREAD

**Issue by pgroenin** [xebialabs-community/xld-complexity-plugin#1]
While attempting to use this plugin and script, I am receiving an error about encoding:

```
pgroenin /c/temp $ /c/Python27/python ci-counter.py
Enter your URL : http://xldinstance
Enter your username : pgroenin
password:
getting Applications
Traceback (most recent call last):
  File "ci-counter.py", line 103, in <module>
    get_Apps()
  File "ci-counter.py", line 19, in get_Apps
    print "getting packages for " + x['ref']
LookupError: unknown encoding: cp65001
pgroenin /c/temp $
```

**Comment by pgroenin** [comment]
Looks like this only happens on my Windows PC. When I run it from a Linux system it appears to work. Probably means this could be closed as an issue only on my end
